name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  cibw_wheels:
    name: Build ${{ matrix.build }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            build: "*x86_64* *i686*"
          - os: ubuntu-18.04
            build: "*aarch64*"
          - os: ubuntu-18.04
            build: "*ppc64le*"
          - os: ubuntu-18.04
            build: "*s390x*"
          - os: windows-2019
            build: "*win_amd64*"
          - os: windows-2019
            build: "*win32*"
          - os: macos-10.15
            build: "*x86_64* *arm64*"

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
        if: runner.os == 'Linux'

      - name: Build wheels
        uses: joerick/cibuildwheel@5514dd28f0e6ab8f584981a98ff86c60b77466ed
        env:
          CIBW_TEST_COMMAND: python -c "import urwid.tests"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_ARCHS_LINUX: "x86_64 i686 aarch64 ppc64le s390x"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_SKIP: "cp27-* cp35-* *-win32"
          CIBW_BUILD: "${{ matrix.build }}"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  check_artifacts:
    name: Check artifacts are correct
    needs: [cibw_wheels]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2

      - name: Check number of downloaded artifacts
        run: |
          ls -al
          find . -name \*.whl | wc -w
        # .github/workflows/wheel-check.sh 24
